version: '3'
services:
  servicio1:
    image: veronica-2529148
    container_name: web
    volumes:
     - C:\Users\PC\Desktop\veronica-2529148\datadrive:/volumen
    ports:
      - 8014:80


  servicio2:
    image: mariadb
    container_name: mariadb1
    environment:
     - MARIADB_ROOT_PASSWORD= mysecretpassword
     - MARIADB_DATABASE= mydb
     - MARIADB_USER= myuser
     - MARIADB_PASSWORD= myuserpassword
    ports:
      - 3306:3306